apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadqyur9111-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadqyur9111-tenant-component
    app.kubernetes.io/part-of: loadqyur9111-tenant-app
  name: loadqyur9111-tenant-component
  namespace: loadqyur9111-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadqyur9111-tenant-component
    weight: null
status: {}
